name: default
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install natsort
        run: |
          python -m pip install natsort
      - name: Install poppler-utils
        run: |
          python -m pip install poppler-utils
      - name: Install poppler-utils agaain via apt-get
        run: |
            sudo apt-get install poppler-utils
      - name: Install pdf2image
        run: |
          python -m pip install pdf2image
      - name: Install PIL
        run: |
          python -m pip install Pillow
      - name: Set up ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - name: Update Policy
        run: |
          sudo sed -i 's#<policy domain="path" rights="none" pattern="@\*"/>#<!-- <policy domain="path" rights="none" pattern="@*"/> -->#' /etc/ImageMagick-6/policy.xml
      - name: Process Image
        working-directory: src/
        run: python generate_js.py
      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: src
          fqdn: thecityandthe.city
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
